default:
	@echo "make install  ...   install into ~/bin"
	@echo "make clean    ...   delete temporary files (from testing)"

clean:
	-rm -f *~ *.eps *.png *.gif *.pdf

install:
	install -m 755 teximage ~/bin
